sha1: ba0ec0c7a9b426e5fc75dd0c00598321a1e1c530
options:
    # paths
    basename: GAMECORE.XFF
    target_path: iso/GAMECORE.XFF
    base_path: ..

    asm_path: asm/gamecore
    src_path: src/gamecore
    build_path: build

    symbol_addrs_path: config/gamecore.symbols.txt
    reloc_addrs_path: config/gamecore.relocs.txt
    create_undefined_funcs_auto: False
    create_undefined_syms_auto: False

    # compiler
    compiler: EEGCC
    platform: ps2

    migrate_rodata_to_functions: True

    string_encoding: EUC-JP
    rodata_string_guesser_level: 2 # improve string detection
    disasm_unknown: True
    named_regs_for_c_funcs: True
    find_file_boundaries: True
    section_order: [".text", ".data", ".rodata", ".lit4", ".sdata", ".sbss", ".bss"]
segments:
    - name: main
      type: code
      start: 0x0
      vram: 0x40010000
      subsegments:
        - [0x0, databin, gamecore_header]
        - [0x63D0, c]
        - [0x1204B0, data]
        - [0x122490, rodata]
        - [0x127920, sbss]
    - [0x1EC4A0]
