sha1: ac00c937b84cbe2e283a97e59e09a11886118388
options:
    # paths
    basename: KERNEL.XFF
    target_path: iso/KERNEL.XFF
    base_path: ..

    asm_path: asm/kernel
    src_path: src/kernel
    build_path: build
    ld_script_path: main.ld

    symbol_addrs_path: config/symbols.kernel.txt
    reloc_addrs_path: config/relocs.kernel.txt
    create_undefined_funcs_auto: False
    # create_undefined_syms_auto: False
    # undefined_funcs_auto_path: config/kernel.auto_funcs.txt
    undefined_syms_auto_path: config/kernel.auto_symbols.txt

    # compiler
    compiler: EEGCC
    platform: ps2

    migrate_rodata_to_functions: True

    string_encoding: EUC-JP
    rodata_string_guesser_level: 2 # improve string detection
    disasm_unknown: True
    named_regs_for_c_funcs: False
    find_file_boundaries: True
    section_order: [".data", ".text", ".rodata", ".lit4", ".sdata", ".sbss", ".bss"]
segments:
    - name: main
      type: code
      start: 0x0
      vram: 0x40010000
      subsegments:
        - [0x0, databin]
        - [0x21A0, c]
    #     - [0x354B0, databin]
    # - [0x63B88]
    - name: 354B0
      align: 8
      type: code
      start: 0x354B0
      vram: 0x10000
      subsegments:
        - [0x354B0, databin]
    - [0x63B88]
